triggers:
  branch:
    - "*"
  pr:
    - "none"

jobs:
  - name: Build Application
    steps:
      - name: Build API & Runner
        run: |
          cd $(SourcesDirectory)/cicd/
          pwd
          make build-all-docker
