triggers:
  branch:
    - "*"
  pr:
    - "none"

jobs:
  - name: Build Application
    steps:
      - name: Build API & Runner
        run: |
          cd $(SourcesDirectory)/cicd
          pwd
          docker login ghcr.io -u spyrosmoux -p ${GH_TOKEN}
          make build-all-docker
