# syntax=docker/dockerfile:1

# Build the application from source
FROM golang:1.21 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /runner cmd/runner/main.go

# Deploy the application binary into a lean image
FROM ubuntu AS build-release-stage
WORKDIR /
COPY --from=build-stage /runner /runner
ENTRYPOINT ["/runner"]
