services:
  api-db:
    image: postgres
    container_name: api-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-api_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-somePassword}
      POSTGRES_DB: ${POSTGRES_DB:-api}

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    image: ghcr.io/spyrosmoux/flowforge-web
    ports:
      - "3000:80"
