services:
  api:
    container_name: api
    image: ghcr.io/spyrosmoux/cicd/api
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    env_file:
      - ../.env.docker
    ports:
      - 8080:8080
