services:
  runner:
    container_name: runner
    image: ghcr.io/spyrosmoux/cicd/runner
    build:
      context: ..
      dockerfile: docker/Dockerfile.runner
    env_file:
      - ../.env.docker
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
