services:
  api:
    container_name: api
    image: ghcr.io/spyrosmoux/cicd/api
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    volumes:
      - ../../flowforge-runner.2024-07-04.private-key.pem:/flowforge-runner.2024-07-04.private-key.pem
    env_file:
      - ../.env.docker
    ports:
      - 8080:8080
